  - name: download WAR file from Nexus repo
    maven_artifact:
      group_id: com.wakaleo.gameoflife
      artifact_id: gameoflife-web
      extension: war
      repository_url: 'http://172.31.33.194:8080/nexus/content/repositories/gol-snapshots/'
      dest: /home/ec2-user/gameoflife-web-latest.war

# Docker container for JMeter
  - name: copy Docker file to aws server
    copy:
      src: ../gameoflife-web/src/test/Dockerfile
      dest: /home/ec2-user/Dockerfile

  - name: build the gol image
    docker_image:
      name: golacc
      tag: latest
      path: /home/ec2-user
      state: present

  - name: run docker container
    docker_container:
      name: golacc_acc_con
      image: golacc:latest
      published_ports: 4000:8080
      state: started
      recreate: yes

# JMeter Directory
  - name: make directory for JMeter
    file:
      path: /home/ec2-user/testing
      state: directory

 # Execute JMeter tests
  - name: copy JMeter tests to aws server
    copy:
      src: ../gameoflife-web/src/test/jmeter
      dest: /home/ec2-user/testing

  - name: copy jmx files into docker container
    command: sudo docker cp testing/jmeter/gameoflife-100-users.jmx golacc_acc_con:/tmp/
  
  - name: run jmx script
    command: sudo docker exec -i golacc_acc_con bash -c '/jmeter/apache-jmeter-2.13/bin/jmeter.sh -Jjmeter.save.saveservice.output_format=xml -n -t /tmp/gameoflife-100-users.jmx -l /tmp/gol-100-users-results.jtl'

  - name: copy results to ec2
    command: docker cp golacc_acc_con:tmp/gol-100-users-results.jtl testing/

  - name: copy jmeter results to workspace
    fetch:
      src: testing/gol-100-users-results.jtl
      dest: ../gameoflife-web/target/
