---
 - name: Install Docker
   hosts: production
   remote_user: ec2-user   
   become: True
   become_user: root
   become_method: sudo
   gather_facts: False
   roles:    
    - docker

 - name: Production Game of Life
   hosts: production
   remote_user: ec2-user
   become: True
   become_user: root
   become_method: sudo
   roles:
    - Game_of_life-Deploy
    
