  - name: download WAR file from Nexus repo
    maven_artifact:
      group_id: com.wakaleo.gameoflife
      artifact_id: gameoflife-web
      extension: war
      repository_url: 'http://172.31.33.194:8080/nexus/content/repositories/gol-releases/'
      dest: /home/ec2-user/gameoflife-web-latest.war

# Docker container for Game of Life
  - name: copy Docker file to aws server
    copy:
      src: ../gameoflife-web/Dockerfile
      dest: /home/ec2-user/Dockerfile

  - name: build the gol image
    docker_image:
      name: golprod
      tag: latest
      path: /home/ec2-user
      state: present

  - name: run docker container
    docker_container:
      name: golprod_prod_con
      image: golprod:latest
      published_ports: 4000:8080
      state: started
      recreate: yes

